# Generated by Django 5.2.8 on 2025-11-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('supertype', models.CharField(max_length=50)),
                ('subtypes', models.CharField(blank=True, max_length=200)),
                ('hp', models.CharField(blank=True, max_length=10)),
                ('types', models.CharField(blank=True, max_length=200)),
                ('rarity', models.CharField(blank=True, max_length=50)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('set_id', models.CharField(blank=True, max_length=50)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
